### PR TITLE
Added status indicator to nodes

### PR DESCRIPTION
**Pull request by FrederikPM**
Simple status indicators for the venv and pip node without any text internationalisation.

### CODE REVIEW

**Comment by 404background** [comment]
Thank you @FrederikPM !
This Pull Request conflicts because I merged the other Pull Request [#7](https://github.com/404background/node-red-contrib-python-venv/pull/7) just before, but I merged and tested it in my local environment.

With the venv node, before running, it showed a green dot and the word Stanby.
image

During running, it showed a blue dot and the words Script is running.
image

When I connected the two, they executed in sequence.
image

I added this, when the error occurred, it showed a red dot and the word error.
image

The pip node is not showing the status, but it may be possible to show it by using spawn of child_process (now execSync).
I will make another Pull Request to verify this.
image

I think it is fine, so I merge this pull request.
With your Pull Request, we are now able to display the status of the node.
Thank you!

**Comment by 404background** [comment]
Thank you @FrederikPM !
This Pull Request conflicts because I merged the other Pull Request [#7](https://github.com/404background/node-red-contrib-python-venv/pull/7) just before, but I merged and tested it in my local environment.

With the venv node, before running, it showed a green dot and the word Stanby.
image

During running, it showed a blue dot and the words Script is running.
image

When I connected the two, they executed in sequence.
image

I added this, when the error occurred, it showed a red dot and the word error.
image

The pip node is not showing the status, but it may be possible to show it by using spawn of child_process (now execSync).
I will make another Pull Request to verify this.
image

About the venv node, could you try it in your environment after merging the latest code?
Below is the venv.js code I tried.

<details>

```
module.exports = function(RED) {
    function Venv(config) {
        RED.nodes.createNode(this,config)
        let node = this

        const fs = require('fs')
        const path = require('path')
        const filePath = path.join(path.dirname(__dirname), 'tmp', this.id + '.py')
        const jsonPath = path.join(path.dirname(__dirname), 'path.json')
        const json = fs.readFileSync(jsonPath)
        const pythonPath = JSON.parse(json).NODE_PYENV_PYTHON

        const child_process = require('child_process')

        node.status({fill:"green",shape:"dot",text:"Standby"})

        node.on('input', function(msg) {
            node.status({fill:"blue",shape:"dot",text:"Script is running"})
            let code = ''
            if(config.code !== null && config.code !== '') {
                code = config.code
            } else {
                code = msg.code
            }
            fs.writeFileSync(filePath, code)

            const message = Buffer.from(JSON.stringify(msg)).toString('base64')
            const args = ['-c', `import base64;import json;msg=json.loads(base64.b64decode(r'${message}'));exec(open(r'${filePath}').read())`]
            const pythonProcess = child_process.spawn(pythonPath, args)
            let stdoutData = ''
            let stderrData = ''

            pythonProcess.on('message', console.log)

            pythonProcess.stdout.on('data', (chunk) => {
                stdoutData += chunk.toString()
            })

            pythonProcess.stderr.on('data', (chunk) => {
                stderrData += chunk.toString()
            })

            pythonProcess.on('close', (exitCode) => {
                if (exitCode !== 0) {
                    node.status({fill:"red",shape:"dot",text:"Error"})
                    node.error(`Error ${exitCode}: ` + stderrData)
                } else {
                    msg.payload = stdoutData
                    node.status({fill:"green",shape:"dot",text:"Standby"})
                    node.send(msg)
                }
                stdoutData = ''
                stderrData = ''
            })
        })
    }
    RED.nodes.registerType("venv", Venv)
}
```

</details>

**Comment by FrederikPM** [comment]
Hi @404background 
I have now merged with main and checked that it works with my environment (Which is the nodered docker container btw).
In addition I couldn't help but add a bit of logic to keep track of the number of running scripts.
Thus, instead of _Script is running_ it now says the following when one or more scripts are running:
billede
If the change is not desired I can ofcourse change it back :)

**Comment by 404background** [comment]
Thank you @FrederikPM !

Sometimes processing can be slow, so it is a good idea to display the number of instances.
It displayed without any problem in my environment.
image

It works fine, so I merge this pull request.
With your Pull Request, we are now able to display the status of the node.
Thank you!

**Pull request merged**
