### PR TITLE
Enable tailing and error propagation for pip node

### PR DESCRIPTION
**Pull request by FrederikPM**
If tail is checked each new line on stdout will be printed separately ending with an empty payload (indicating that the process is finished).
Also enable propagating error(s) to the error node.

### CODE REVIEW

**Comment by FrederikPM** [comment]
Heres a flow for testing:
```
[    {        "id": "0edbb2df88e03bd3",        "type": "pip",        "z": "7a7ae303f662be9f",        "venvconfig": "4657b6fbdbaf6f7e",        "name": "Install",        "arg": "numpy sqlalchemy psycopg2-binary scipy picoquake",        "action": "install",        "tail": true,        "x": 370,        "y": 360,        "wires": [            [                "d4e0b553828cc75c"            ]        ]    },    {        "id": "1e2949770915b31c",        "type": "pip",        "z": "7a7ae303f662be9f",        "venvconfig": "4657b6fbdbaf6f7e",        "name": "Uninstall",        "arg": "numpy sqlalchemy psycopg2-binary scipy picoquake",        "action": "install",        "tail": true,        "x": 360,        "y": 460,        "wires": [            [                "34a8f20e642d26ad"            ]        ]    },    {        "id": "abbaba821185a985",        "type": "inject",        "z": "7a7ae303f662be9f",        "name": "",        "props": [],        "repeat": "",        "crontab": "",        "once": false,        "onceDelay": 0.1,        "topic": "",        "x": 150,        "y": 360,        "wires": [            [                "0edbb2df88e03bd3"            ]        ]    },    {        "id": "bf675d2076877306",        "type": "inject",        "z": "7a7ae303f662be9f",        "name": "",        "props": [],        "repeat": "",        "crontab": "",        "once": false,        "onceDelay": 0.1,        "topic": "",        "x": 150,        "y": 460,        "wires": [            [                "1e2949770915b31c"            ]        ]    },    {        "id": "d4e0b553828cc75c",        "type": "debug",        "z": "7a7ae303f662be9f",        "name": "debug 2",        "active": true,        "tosidebar": true,        "console": false,        "tostatus": false,        "complete": "false",        "statusVal": "",        "statusType": "auto",        "x": 600,        "y": 440,        "wires": []    },    {        "id": "34a8f20e642d26ad",        "type": "debug",        "z": "7a7ae303f662be9f",        "name": "debug 3",        "active": true,        "tosidebar": true,        "console": false,        "tostatus": false,        "complete": "false",        "statusVal": "",        "statusType": "auto",        "x": 600,        "y": 520,        "wires": []    },    {        "id": "4657b6fbdbaf6f7e",        "type": "venv-config",        "venvname": "pyenv",        "version": "default"    }]
```

**Comment by FrederikPM** [comment]
By the way. It would be much appreciated if you could release a new version of the node when this change is merged.

**Comment by 404background** [comment]
Thank you @FrederikPM !

I tested the flow.
When I run pip install and an error occurs, I get the following error.
スクリーンショット 2024-07-11 131558

The error is that "code" on line 100 of pip.js is not defined.
This was resolved by changing it to "exitCode".
Could you please confirm this?

**Comment by 404background** [comment]
If Tail is false, results were displayed after the execution finished.
If Tail is true, results were displayed for each package.
image
This seems more useful if there are many packages.
Also, I checked that the error node catch the error.

**Comment by FrederikPM** [comment]
Ah yes, that is correct. I forgot to rename the variable to exitCode.

**Comment by 404background** [comment]
Thank you @FrederikPM for the confirmation!
OK, I will merge this Pull Request and fix the code.
I will also release it as a new version.

**Pull request merged**
